/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Mediador.Registro;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import tablas.Alumnos;


/**
 *
 * @author renne
 */
public class MosstrarAlumno extends javax.swing.JFrame {

    /**
     * Creates new form MosstrarAlumno
     */
    public MosstrarAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxt_buscarrut = new javax.swing.JTextField();
        jbtn_buscaralumno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_datosalumnos = new javax.swing.JTable();
        jbtn_salirmostalum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("RUT:");

        jtxt_buscarrut.setText("sin digito verificador");
        jtxt_buscarrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_buscarrutActionPerformed(evt);
            }
        });

        jbtn_buscaralumno.setText("Buscar");
        jbtn_buscaralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscaralumnoActionPerformed(evt);
            }
        });

        jtbl_datosalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Curso", "Pase de movilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbl_datosalumnos);

        jbtn_salirmostalum.setText("Salir");
        jbtn_salirmostalum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salirmostalumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_buscarrut, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jbtn_buscaralumno))
                    .addComponent(jbtn_salirmostalum, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_buscarrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscaralumno))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jbtn_salirmostalum)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_buscaralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscaralumnoActionPerformed
        
        String nombre,apellido,curso;
        boolean pase_movilidad;
        int rut,idalumno;
        
        Registro reg = new Registro();
        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_datosalumnos.getModel();
        
        try {
            
            rut = Integer.parseInt(this.jbtn_buscaralumno.getText());
            
            
        } catch (Exception e) {
            rut = 0;
        }
        modelo.setRowCount(0);
        if (rut == 0){
           List<Alumnos> lista =  reg.buscarTodos();
           
            for (Alumnos alumno : lista) {
                
                nombre = alumno.getNombre();
                apellido = alumno.getApellido();
                curso = alumno.getCurso();
                pase_movilidad = alumno.isPase_movilidad();                            
            
            modelo.addRow(new Object [] {nombre,apellido,curso,pase_movilidad});
                
            }
            
        } else {
            
            Alumnos alumno = reg.buscarporrut(rut);
        }
        
        
        
    }//GEN-LAST:event_jbtn_buscaralumnoActionPerformed

    private void jtxt_buscarrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_buscarrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_buscarrutActionPerformed

    private void jbtn_salirmostalumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salirmostalumActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_salirmostalumActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MosstrarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MosstrarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MosstrarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MosstrarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MosstrarAlumno().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_buscaralumno;
    private javax.swing.JButton jbtn_salirmostalum;
    private javax.swing.JTable jtbl_datosalumnos;
    private javax.swing.JTextField jtxt_buscarrut;
    // End of variables declaration//GEN-END:variables
}
